### ISSUE TITLE
Conflict with dlh_googlemaps

### ISSUE THREAD

**Issue by Balindil** [designs2/foundation-to-contao#12]
'Google Map' lässt sich weder als Inhaltselement, noch als Modul einsetzen, wenn foundation-to-contao installiert ist. Es erscheint die Meldung: 'Fatal error: Class 'DlhGooglemapsElementsModel' not found in /xxxx/system/modules/core/library/Contao/Model/Collection.php on line 146'

Nach Deinstallation von foundation-to-contao funktioniert dlh_googlemaps wie gewohnt!

**Comment by MoniqueHahnefeld** [comment]
have to fix #24
