### ISSUE TITLE
Beim neusyncronisieren Fehler

### ISSUE THREAD

**Issue by csaeum** [designs2/foundation-to-contao#27]
Diesen Fehler bekomme ich wenn ich im Composer auf Neusyncronisierung gehe:

Warning: copy(/kunden/341138_96328/webseiten/Contao-alle-Domains-Foundation/composer/vendor/designs2/foundation-to-contao/files-package/theme/foundation): failed to open stream: No such file or directory in composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/AbstractInstaller.php on line 560

#0 [internal function]: __error(2, 'copy(/kunden/34...', '/kunden/341138_...', 560, Array)
#1 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/AbstractInstaller.php(560): copy('/kunden/341138_...', '/kunden/341138_...')
#2 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/AbstractInstaller.php(471): ContaoCommunityAlliance\Composer\Plugin\AbstractInstaller->installFiles('/kunden/341138_...', '/kunden/341138_...', 'files/themes/fo...')
#3 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/AbstractInstaller.php(178): ContaoCommunityAlliance\Composer\Plugin\AbstractInstaller->updateUserfiles(Object(Composer\Package\CompletePackage))
#4 system/modules/!composer/src/Controller/ResyncController.php(86): ContaoCommunityAlliance\Composer\Plugin\AbstractInstaller->updateContaoFiles(Object(Composer\Package\CompletePackage))
#5 system/modules/!composer/src/ClientBackend.php(218): ContaoCommunityAlliance\Contao\Composer\Controller\ResyncController->handle(Object(Contao\Input))
#6 system/modules/core/classes/Backend.php(406): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#7 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('composer')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}

**Comment by MoniqueHahnefeld** [comment]
Hi, welche Version von Contao?

**Comment by csaeum** [comment]
Sorry total vergessen:
Contao 3.4.4
aber im Forum hast du ja schon geschrieben das es für dies noch net ausgelegt ist. Also wird das ein "normaler Fehler" sein.
