### ISSUE TITLE
 not in Layout

### ISSUE THREAD

**Issue by mirkogleibe** [designs2/foundation-to-contao#28]
Irgendwie scheint es das bei mir im Menü nicht aufzutauchen. Muss man das nach Install noch irgendwo aktivieren? 
Contao 3.5.2 mit Version aus ER.
Oder sehe ich den Wald vor Bäumen nicht?

**Comment by mirkogleibe** [comment]
keinerlei Datenbankgedöns während der Installation. Normal?!?

**Comment by mirkogleibe** [comment]
Bei dem Versuch eventuell das Foundation Grid von dir nachzuschieben...
```
The module dependencies could not be resolved.

Array
(
    [codeowl_grid_control] => Array
        (
            [0] => codeowl_design_presets
        )

)
```

**Comment by mirkogleibe** [comment]
Im Ordner files gibt es nach dem Install einen Ordner TL_ROOT mit den DIngen, die zum Modul gehören. 
Kann es sein, dass da irgendwas falsch bei der Ordnerzuweisung ist?

**Comment by MoniqueHahnefeld** [comment]
https://github.com/designs2/foundation-to-contao/blob/develop/README.md

**Comment by mirkogleibe** [comment]
Öhmm. Ich meinte das durchaus als Fehlermeldung. Die Dateien werden nicht da hingeschoben wo sie hinsollen. Liegen alle im Ordner files/TL_ROOT und nicht in files/ system/

**Comment by MoniqueHahnefeld** [comment]
Lies bitte die news:
 http://www.designs2.de/i/news/news-details/items/neue-version-von-foundation-to-contao.html
