### ISSUE TITLE
codeowl_fw_foundation lässt sich nicht aktivieren

### ISSUE THREAD

**Issue by kissmedve** [designs2/foundation-to-contao#29]
Contao 3.5.3.
- designs2/codeowl_design_presets   1.0.2
- designs2/codeowl_fw_foundation    1.1.1
- designs2/codeowl_grid_control 1.0.0
  installiert mit Composer. 

Aktualisieren der Pakete bringt:

> Fatal error: Uncaught exception Exception with message Query error: 
> Table 'xxx.tl_co_foundation_settings' doesn't exist 
> (SELECT \* FROM tl_co_foundation_settings) 
> thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

.skip eingefügt wie [beschrieben](https://github.com/designs2/codeowl_fw_foundation/wiki/Update-FTC-zu-Codeowl-Framework-Foundation-1.0.0)  und Pakete aktualisiert.
.skip wieder gelöscht.
Klick auf Button FW_Einstellungen ergibt Fehlermeldung.
Error Log:

> PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: 
> Table 'xxx.tl_co_foundation_settings' doesn't exist 
> (SELECT \* FROM tl_co_foundation_settings ORDER BY name)' thrown in 
> /var/www/virtual/xxx/html/contao/system/modules/core/library/Contao/Database/Statement.php on line 295

Damit ist nur codeowl_grid_control nutzbar, alle weiteren Funktionen, die über codeowl_fw_foundation laufen, können nicht aktiviert werden. 

Nach dem Installieren der Pakete als Legacy-Version führt gibt es übrigens gar keinen Button FW_Einstellungen, wobei codeowl_fw_foundation in den Einstellungen nicht deaktiviert ist.

**Comment by MoniqueHahnefeld** [comment]
Das Workaround ist mit der Contao-Version 3.4. getestet, weil diese Erweiterung nur bis dahin freigegeben war. Du kannst gerne eine Support-Anfrage an mich richten, dann schaue ich mir deine Installation an.

**Comment by kissmedve** [comment]
Hallo Monique,

vielen Dank für die Auskunft!

Ich bin jetzt von Foundation zu Bootstrap gewechselt, das funktioniert 
fürs Erste gut. Die Klasseneingabe ist zwar nicht so komfortabel für den 
Kunden, aber auch nicht soo wichtig.

Viele Grüße
Ursula

Am 11.10.2015 um 15:46 schrieb Monique Hahnefeld:

> Das Workaround ist mit der Contao-Version 3.4. getestet, weil diese 
> Erweiterung nur bis dahin freigegeben war. Du kannst gerne eine 
> Support-Anfrage an mich richten, dann schaue ich mir deine 
> Installation an.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/designs2/foundation-to-contao/issues/29#issuecomment-147193223.

## 

Webberie
Selzenstr. 3 / 79280 Au

Tel. 0761 4567804
ursula.gottschall@webberie.de

www.webberie.de
